export const QA_RUN = {
  supplier: {
    name: "QA Rovos Test Operator",
    kind: "train_operator",
    email: "ops@qa-rovos.test",
    phone: "+27 11 555 0100",
    website: "https://qa-rovos.test",
    location: "Pretoria, South Africa",
    notes: "Created by automated QA suite - safe to delete.",
    routeName: "QA Pretoria to Cape Town",
    suiteTypeName: "Deluxe Suite",
  },
  package: {
    name: "QA Pride of Africa 4-Night",
    durationNights: 4,
    currency: "ZAR",
    singleSupplementPct: 50,
    fixedPricePerPerson: 45000,
  },
  customer: {
    title: "Mr",
    firstName: "James",
    lastName: "Whitmore",
    email: "james.whitmore+qa@example.com",
    phone: "+44 7700 900123",
    country: "United Kingdom",
    province: "Greater London",
    vipStatus: false,
    notes: "QA fixture - automated suite.",
  },
  job: {
    travelDateStart: "2026-09-12",
    travelDateEnd: "2026-09-16",
    paxAdults: 2,
    paxChildren: 0,
    purpose: "leisure",
    source: "website",
  },
} as const
